version: '2.1'

services:
  #  configserver:
  #    build: ConfigServer
  #    mem_limit: 512m
  #    ports:
  #      - "8888:8888"
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      backend:
  #        aliases:
  #          - "configserver"

  eurekaserver:
    build: discovery
    mem_limit: 512m
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    depends_on:
    #      configserver:
    #        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"

  customer:
    build: customer
    mem_limit: 512m
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
#      customer-db:
#        condition: service_healthy
      #      configserver:
      #        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "customer"

  account:
    build: account
    mem_limit: 512m
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
#      account-db:
#        condition: service_healthy
      #      configserver:
      #        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "account"
  card:
    build: card
    mem_limit: 512m
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
#      card-db:
#        condition: service_healthy
      #      configserver:
      #        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "card"
  composite:
    build: composite
    mem_limit: 512m
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "composite"

  gateway:
    build: gateway
    mem_limit: 512m
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      #      configserver:
      #        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"

networks:
  backend:
    name: concept-banking
    driver: bridge