global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['customer:8080']
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'account:8080' ]
  - job_name: 'card-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'card:8080' ]
  - job_name: 'composite-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'composite:8080' ]
  - job_name: 'edge-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway:8080' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8080' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8080' ]