server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/usmansaeedm001/config
          username: usmansaeedm001
          password: 0kd0n3@Github.123
          clone-on-start: true
          refresh-rate: 10
          timeout: 300
          default-label: master

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
#springdoc:
#  swagger-ui:
#    path: /mus/openbanking/ui
#  api-docs:
#    enabled: true
#    path: /mus/openbanking/docs
#  use-management-port: true
